[package]
name = "vtdl-core"
version.workspace = true
edition.workspace = true

[dependencies]
shared.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
thiserror.workspace = true
base64.workspace = true
tokio = { version = "1", features = ["rt", "sync", "macros", "time"] }

reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
directories = "5"
toml = "0.8"
keyring = { version = "3", features = ["async-secret-service", "tokio", "crypto-rust"] }
